### ISSUE TITLE
Problems with async

### ISSUE THREAD

**Issue by jwatzman** [hhvm/hack-langspec#12]
https://github.com/hhvm/hack-langspec/blob/master/spec/10-expressions.md#expressions should probably mention `await`. Might be missing in other syntax specifiers too.

> When an async function is compiled, a special transformation is performed, so that an object that implements Awaitable<T> (§§) is returned to the caller (where T is the function's return-type).

Need to check the definition of return-type, but this transform happens at runtime, the static return type is still always `Awaitable<T>`, that's what you write down in the source file.

> When yielding control, the implementation of await may choose to yield control back to the current async function's caller.

Not sure what this is getting at here since the caller is still blocked.

**Comment by JoelMarcey** [comment]
I think fixed by: fa004145b220c5e49da65f52fa6d6b4bcc1c9fb4
