### ISSUE TITLE
Special comments such as HH_FIXME

### ISSUE THREAD

**Issue by SiebelsTim** [hhvm/hack-langspec#15]
Shouldn't these be mentioned here as well?

`spec/23-differences-from-php.md => Lexical Structure => Comments`

**Comment by fredemmott** [comment]
#10 has some discussion about this

**Comment by SiebelsTim** [comment]
@fredemmott What about `partial` and `decl` then?

**Comment by fredemmott** [comment]
"This specification is written from the perspective of strict mode only. A conforming implementation may provide modes other than strict, but they are outside the scope of this specification."

We don't currently want to change that.
