### ISSUE TITLE
"void" enhancements

### ISSUE THREAD

**Issue by jwatzman** [hhvm/hack-langspec#32]
@elgenie tweaked the way we deal with `void` to be more in line with what you'd expect. We also reserved `$_` to always be of type `void`. I think the spec goes on at some length about the issues with the former; we can remove most of that. Then we need to add the latter.

**Comment by RexJaeschke** [comment]
I've just made a pull request (Branch 008-Misc-nits-1) that cleans up the void-related stuff.
